# Quantizes the XOR reference model and generates the Foundry test
# (test/BlockNetInference.t.sol) with REAL vectors: every expected class
# and every expected 16-block state comes from the Python int_forward,
# which the contract must reproduce exactly.
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from blockz10_neural import BlockNet, xor  # noqa: E402
from blockz10_neural.quantize import (  # noqa: E402
    QBASE, int_forward, quantize_input, quantize_model,
)

net = BlockNet.load(ROOT / "docs" / "assets" / "models" / "xor.json")
q = quantize_model(net)

# --- vectors: the 4 XOR points + 6 seeded random feature vectors -----------
f_xor, y_xor = xor()
rng = np.random.default_rng(155)
inputs = [quantize_input(f) for f in f_xor]
labels = list(y_xor)
for _ in range(6):
    inputs.append(quantize_input(rng.random(2)))
    labels.append(None)  # free vectors: parity only

vectors = []
for x in inputs:
    cls, state = int_forward(q, x)
    vectors.append((list(map(int, x)), cls, list(map(int, state))))

for k, want in enumerate(labels[:4]):
    assert vectors[k][1] == want, "quantized XOR must stay perfect"

# --- emit the Solidity test --------------------------------------------------
W = q["thetas_q"]
flat = [int(W[r][i][j]) for r in range(q["rounds"])
        for i in range(16) for j in range(16)]


def chunks(seq, n):
    for i in range(0, len(seq), n):
        yield seq[i:i + n]


w_lines = "\n".join(
    "        " + " ".join(f"w[{i}] = {v};" for i, v in row)
    for row in chunks(list(enumerate(flat)), 8))

bias_lines = "\n".join(
    f"        b[{c}] = int256({v});" for c, v in enumerate(q["bias_q"]))


def arr16(vals):
    return "[" + ", ".join(f"uint256({v})" for v in vals) + "]"


vec_cases = []
for k, (x, cls, state) in enumerate(vectors):
    vec_cases.append(f"""
    function test_Vector{k}() public view {{
        uint256[16] memory x = {arr16(x)};
        (uint256 cls, uint256[16] memory s) = net.forward(x);
        require(cls == {cls}, "class mismatch v{k}");
        uint256[16] memory want = {arr16(state)};
        for (uint256 i = 0; i < 16; i++) require(s[i] == want[i], "state mismatch v{k}");
    }}""")

sol = f"""// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// GENERATED by tools/export_contract.py — do not edit by hand.
// Every expected value below was produced by the Python fixed-point
// reference (src/blockz10_neural/quantize.py) on the trained XOR model;
// the contract must reproduce it bit for bit.

import {{BlockNetInference}} from "../contracts/BlockNetInference.sol";

contract BlockNetInferenceTest {{
    BlockNetInference internal net;

    function _weights() internal pure returns (uint32[] memory w) {{
        w = new uint32[]({len(flat)});
{w_lines}
    }}

    function _bias() internal pure returns (int256[] memory b) {{
        b = new int256[]({q['classes']});
{bias_lines}
    }}

    function setUp() public {{
        net = new BlockNetInference({q['rounds']}, {q['classes']}, int256({q['scale_q']}), _bias(), _weights());
    }}
{''.join(vec_cases)}

    function test_RevertsOnBadDeposit() public {{
        uint256[16] memory x;
        x[1] = 123; // sum != BASE
        (bool ok2,) = address(net).staticcall(
            abi.encodeWithSelector(net.forward.selector, x));
        require(!ok2, "must revert on bad deposit");
    }}

    function test_RevertsOnNonConservativeColumn() public {{
        uint32[] memory w = _weights();
        w[0] += 1; // break column 0 of round 0
        (bool ok2,) = address(this).call(
            abi.encodeWithSignature("deployBad(uint32[])", w));
        require(!ok2, "constructor must reject a non-conservative column");
    }}

    function deployBad(uint32[] memory w) external {{
        new BlockNetInference({q['rounds']}, {q['classes']}, int256({q['scale_q']}), _bias(), w);
    }}

    function test_WeightIntrospection() public view {{
        require(net.weightAt(0, 0, 0) == {flat[0]}, "w[0][0][0]");
        require(net.weightAt({q['rounds'] - 1}, 15, 15) == {flat[-1]}, "last weight");
        require(net.biasAt(0) == int256({q['bias_q'][0]}), "bias 0");
    }}

    function test_ColumnsSumToBase() public view {{
        for (uint256 r = 0; r < {q['rounds']}; r++) {{
            for (uint256 j = 0; j < 16; j++) {{
                uint256 s = 0;
                for (uint256 i = 0; i < 16; i++) s += net.weightAt(r, i, j);
                require(s == 1e9, "column must sum to BASE");
            }}
        }}
    }}
}}
"""
out = ROOT / "test" / "BlockNetInference.t.sol"
out.parent.mkdir(exist_ok=True)
out.write_text(sol, encoding="utf-8")
print(f"wrote {out} ({len(vectors)} parity vectors)")
print(f"quantized xor classes: {[v[1] for v in vectors[:4]]} (expect [0,1,1,0])")
